const $=s=>document.querySelector(s);const state={lang:localStorage.getItem('vbd-lang')||'vi'};
const langs=[['vi','🇻🇳','Tiếng Việt'],['en','🇬🇧','English']];
const T={vi:{filesNav:'Tệp chia sẻ',badge:'Nguyen Van Bao · Digital',title:'Nền tảng số<br><span>gọn, đẹp & hữu ích.</span>',lead:'Một giao diện tối giản cho các tiện ích, tài nguyên và tệp được chia sẻ.',browse:'Khám phá tệp',aboutBtn:'Giới thiệu',downloadTitle:'Tải tệp',downloadDesc:'Tài nguyên được chia sẻ',toolsTitle:'Tiện ích',toolsDesc:'Giao diện gọn, dễ dùng',features:'Một vài chức năng',privateTitle:'Tệp riêng tư',privateDesc:'Tệp chỉ hiển thị khi chủ web đã chủ động chia sẻ.',fastTitle:'Nhanh & gọn',fastDesc:'Thiết kế ưu tiên điện thoại, ít thành phần thừa và thao tác rõ ràng.',simpleTitle:'Đơn giản',simpleDesc:'Không nhồi số liệu hay lời quảng cáo không cần thiết.',sharedTitle:'Tệp được chia sẻ',loading:'Đang tải danh sách tệp…',aboutTitle:'Nguyen Van Bao',aboutDesc:'Một không gian nhỏ dành cho tiện ích và tài nguyên số. Tập trung vào trải nghiệm sạch, nhanh và dễ dùng.'},en:{filesNav:'Shared files',badge:'Nguyen Van Bao · Digital',title:'A digital platform<br><span>simple, clean & useful.</span>',lead:'A minimal space for utilities, resources and files shared by the site owner.',browse:'Browse files',aboutBtn:'About',downloadTitle:'Download files',downloadDesc:'Shared resources',toolsTitle:'Utilities',toolsDesc:'Clean and easy to use',features:'A few features',privateTitle:'Private files',privateDesc:'Files appear only when the site owner chooses to share them.',fastTitle:'Fast & clean',fastDesc:'Mobile-first design with fewer distractions and clear actions.',simpleTitle:'Simple',simpleDesc:'No fake numbers or unnecessary marketing claims.',sharedTitle:'Shared files',loading:'Loading files…',aboutTitle:'Nguyen Van Bao',aboutDesc:'A small space for digital utilities and resources, focused on a clean, fast and simple experience.'}};
function applyLang(code){state.lang=code;localStorage.setItem('vbd-lang',code);const d=T[code],x=langs.find(a=>a[0]===code)||langs[0];$('#flag').textContent=x[1];$('#langCode').textContent=code.toUpperCase();document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=d[e.dataset.i18n]??e.textContent);document.querySelectorAll('[data-i18n-html]').forEach(e=>e.innerHTML=d[e.dataset.i18nHtml]??e.innerHTML);}
langs.forEach(([c,f,n])=>{let b=document.createElement('button');b.textContent=`${f}  ${n}`;b.onclick=()=>{applyLang(c);$('#langMenu').classList.remove('open')};$('#langMenu').appendChild(b)});$('#langBtn').onclick=e=>{e.stopPropagation();$('#langMenu').classList.toggle('open')};document.addEventListener('click',()=>$('#langMenu').classList.remove('open'));applyLang(state.lang);
async function loadFiles(){const box=$('#fileList');try{const r=await fetch('/api/files');if(!r.ok)throw Error();const data=await r.json();if(!data.files.length){box.innerHTML='<div class="empty">'+(state.lang==='en'?'No shared files yet.':'Chưa có tệp được chia sẻ.')+'</div>';return}box.innerHTML=data.files.map(f=>`<div class="file"><div class="file-icon">⇩</div><div class="file-info"><b>${escapeHtml(f.pathname.split('/').pop())}</b><small>${formatBytes(f.size)} · ${new Date(f.uploadedAt).toLocaleDateString()}</small></div><a class="download" href="${f.url}" target="_blank" rel="noopener">${state.lang==='en'?'Download':'Tải xuống'}</a></div>`).join('')}catch(e){box.innerHTML='<div class="empty">'+(state.lang==='en'?'File storage is not configured yet.':'Kho tệp chưa được cấu hình.')+'</div>';}}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function formatBytes(n){if(!n)return '0 B';let u=['B','KB','MB','GB'],i=Math.floor(Math.log(n)/Math.log(1024));return (n/1024**i).toFixed(i?1:0)+' '+u[i]}
loadFiles();
const audio=$('#audio'),play=$('#play');play.onclick=()=>audio.paused?(audio.play(),play.textContent='❚❚'):(audio.pause(),play.textContent='▶');audio.onended=()=>play.textContent='▶';audio.ontimeupdate=()=>$('#time').textContent=`${String(Math.floor(audio.currentTime/60)).padStart(2,'0')}:${String(Math.floor(audio.currentTime%60)).padStart(2,'0')}`;$('#prev').onclick=()=>audio.currentTime=0;$('#next').onclick=()=>audio.currentTime=Math.min(audio.duration||0,audio.currentTime+10);

// Compact 7-color robot verification gate (local UX gate, not a security CAPTCHA)
(function(){
 const gate=$('#robotGate'), btn=$('#robotCheck'), status=$('#robotStatus'), title=$('#robotTitle'), desc=$('#robotDesc'), text=$('#robotBtnText');
 if(!gate||!btn)return;
 if(localStorage.getItem('vbd-robot-verified')==='1'){gate.classList.add('hide');return;}
 btn.onclick=()=>{
   btn.classList.add('loading'); text.textContent=state.lang==='en'?'Checking…':'Đang kiểm tra…'; status.textContent=state.lang==='en'?'Running a quick check…':'Đang xác minh nhanh…';
   setTimeout(()=>{btn.classList.remove('loading');btn.classList.add('verified');text.textContent=state.lang==='en'?'Verified':'Đã xác minh';status.textContent=state.lang==='en'?'Verification complete':'Xác minh thành công';localStorage.setItem('vbd-robot-verified','1');setTimeout(()=>gate.classList.add('hide'),450)},1200);
 };
})();
